/* props/taiwan-1.92: hTC Asia TW: HTC__621 */
static bool is_variant_taiwan(std::string bootcid) {
    if (bootcid == "HTC__621") return true;
    return false;
}

static const char *htc_taiwan_properties =
    "ro.build.fingerprint=htc/pmeuhl_00709/htc_pmeuhl:6.0.1/MMB29M/790517.1:user/release-keys\n"
    "ro.build.product=htc_pmeuhl\n"
    "ro.product.device=htc_pmeuhl\n"
    "ro.product.model=HTC_M10h\n"
    "ro.product.model=MSM8996 for arm64\n"
    "ro.ril.oem.ecclist=112,911,110,119\n"
    "ro.ril.enable.amr.wideband=0\n"
    "ro.ril.enable.sdr=1\n"
    "ro.ril.enable.pre_r8fd=1\n"
    "ro.ril.fd.pre_r8_tout.scr_off=2\n"
    "ro.ril.fd.pre_r8_tout.scr_on=3\n"
    "ro.ril.enable.r8fd=1\n"
    "ro.ril.fd.r8_tout.scr_off=3\n"
    "ro.ril.fd.r8_tout.scr_on=3\n"
    "ro.ril.air.enabled=1\n"
    "ro.ril.gsm.to.lte.blind.redir=1\n"
    "ro.ril.ltefgi=2144337598\n"
    "ro.ril.ltefgi.rel9=3221225472\n"
    "ro.ril.pdpnumber.policy.roaming=3\n"
    "ro.ril.hsxpa=5\n"
    "ro.ril.hsdpa.category=24\n"
    "ro.ril.hsupa.category=6\n"
    "ro.ril.disable.cpc=1\n"
    "ro.ril.asia.tw.ecc.feature=1\n"
    "persist.rild.nitz_plmn=\n"
    "persist.rild.nitz_long_ons_0=\n"
    "persist.rild.nitz_long_ons_1=\n"
    "persist.rild.nitz_long_ons_2=\n"
    "persist.rild.nitz_long_ons_3=\n"
    "persist.rild.nitz_short_ons_0=\n"
    "persist.rild.nitz_short_ons_1=\n"
    "persist.rild.nitz_short_ons_2=\n"
    "persist.rild.nitz_short_ons_3=\n"
    "ril.subscription.types=NV,RUIM\n"
    "telephony.lteOnCdmaDevice=1\n"
    "telephony.lteOnCdmaDevice=0\n"
    "persist.radio.fill_eons=1\n"
    "persist.igps.sensor=on\n"
    "persist.radio.custom_ecc=1\n"
    "persist.radio.apm_sim_not_pwdn=0\n"
    "persist.radio.apm_mdm_not_pwdn=1\n"
    "persist.radio.cs_srv_type=1\n"
    "ro.telephony.default_network=9\n"
    "persist.radio.sap_silent_pin=1\n"
    "ro.gps.agps_provider=1\n"
;
